### ISSUE TITLE
Soucis sur le changement des fils de message

### ISSUE THREAD

**Issue by Wivik** [francois-dorin/previnpact-extension#8]
Hello,

Deux soucis observés sur la feature expérimentale pour l'affichage des fils de commentaires : 

Le bouton "Editer" disparaît et la citation n'est pas prise en compte. C'est comme si cela ne marchait pas pour son propre profile.

Avant : 

![image](https://github.com/francois-dorin/previnpact-extension/assets/48727868/48cc5c97-88ba-426e-8335-7f094caff72d)

Après : 

![image](https://github.com/francois-dorin/previnpact-extension/assets/48727868/f9aba31d-ae80-459b-94b9-05330f21e8a8)

**Comment by francois-dorin** [comment]
Autre bogue que je viens de détecter : lors du changement de vue, on perd la fonctionnalité pour répondre à un message. Le bouton est là, mais si on vient de changer de vue et qu'on clique sur répondre, le bouton disparait, tout simplement.

**Comment by francois-dorin** [comment]
Alors, pour la citation, j'ai peut être compris ce que tu voulais dire, mais si c'est ça, c'est le comportement actuel du site.

Si on répond à un message de niveau 1, la citation n'apparait pas lors de la réponse. Par contre, si on répond à une réponse, il y a bien une citation. Est-ce de cela dont tu voulais parler ? Si oui, c'est ainsi sur Next.

Et j'ai testé en répondant avec la vue chronologique à ton commentaire, et j'ai bien eu la citation qui est apparue.

**Comment by francois-dorin** [comment]
Bon a priori, j'ai réussi à corriger les bogues. Je ferme donc le ticket (mais on le rouvrira si nécessaire)
